name: Github Actions 실행시키기

on:
  push:
    branches:
      - main

jobs:
  Jobs-Names-run_name_demo-01:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "Run Workflows - run_name_demo"

      - name: Secret Test
        run: |
          echo ${${secrets.MY_PASSWORD}}
