name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4 # 라이브러리

      - name: build
        run: npm run build

      - name: Debugging
        run: |
          ls
          cd dist
          ls
